let a = [
  {
    id: 1,
    name: 'Biryani',
    image_url: require('../../../assets/items/biryani.png'),
    category: 'Non-Veg',
    sub_category: 'Rice',
  },
  {
    id: 2,
    name: 'Pizza',
    image_url: require('../../../assets/items/pizza.jpg'),
    category: 'Fast Food',
    sub_category: 'Italian',
  },
  {
    id: 3,
    name: 'Butter',
    image_url: require('../../../assets/items/paneer.png'),
    category: 'Veg',
    sub_category: 'Curry',
  },
  {
    id: 4,
    name: 'Burger',
    image_url: require('../../../assets/items/burger.png'),
    category: 'Fast Food',
    sub_category: 'American',
  },
  {
    id: 5,
    name: 'samosa',
    image_url: require('../../../assets/items/samosa.jpg'),
    category: 'Asian',
    sub_category: 'Chinese',
  },
  {
    id: 6,
    name: 'sweets',
    image_url: require('../../../assets/items/sweets.png'),
    category: 'Dessert',
    sub_category: 'Bakery',
  },
  {
    id: 7,
    name: 'kabab',
    image_url: require('../../../assets/items/kabab.png'),
    category: 'Meal',
    sub_category: 'Indian',
  },
];

export let listOFCategory = [...a];
// show restrount on the shorting of number of order and rating : high rating show first

export const listOFRestrount = [
  {
    id: 1,
    createdAt: '',
    modifyAt: '',
    openStatus: true,
    startAt: '',
    closeAt: '',
    restrountImage: '',
    name: 'Vishnu Story Fast Food House',
    shortName: 'VR House',
    mode: 'non-veg',
    location: 'Near Gadh devi mandir Toota pool, ranka more garhwa', // show only on the view of order restrount
    restrountOffer: 'Get 50% Off on every order',
    rating: '4.2',
    distance: '1 Km', // calulcate dynamic on the time of render and carding time
    averageDeliveryTime: '20 mins', // calculate on the backend on the gettting time
    description: '', // show only at the view of restrount page
    licenceNumber: '',
    ownerName: '',
    averageCookingTime: '',
    homeBanner: [
      {
        id: 1,
        url: require('../../../assets/restrount-welcome-img/biryani1.jpg'),
      },
      {
        id: 2,
        url: require('../../../assets/restrount-welcome-img/biryani2.jpg'),
      },
      {
        id: 3,
        url: require('../../../assets/restrount-welcome-img/biryani3.jpg'),
      },
    ],
  },
  {
    id: 2,
    createdAt: '',
    modifyAt: '',
    openStatus: false,
    startAt: '',
    closeAt: '',
    restrountImage: '',
    name: 'Good Food Kitchen',
    mode: 'veg,non-veg',
    location: 'Chiniya More',
    restrountOffer: 'Get 10% Off on Selected order',
    rating: '3.5',
    distance: '1.5Km', // calulcate dynamic on the time of render and carding time (bases of last location saved)
    averageDeliveryTime: '20min', // calculate on the backend on the gettting time (bases of last location order)
    description: '',
    licenceNumber: '',
    ownerName: '',
    homeBanner: [
      {
        id: 1,
        url: require('../../../assets/restrount-welcome-img/dalmakhni3.jpg'),
      },
      {
        id: 2,
        url: require('../../../assets/restrount-welcome-img/dalmakhni2.jpg'),
      },
      {
        id: 3,
        url: require('../../../assets/restrount-welcome-img/dalmakhni1.jpg'),
      },
    ],
  },
];

export const listOfItem = [
  {
    id: 1,
    name: 'Hayedrabadi biryani',
    url: require('../../../assets/items/biryani.png'),
    price: 250,
    ladoPrice: 299,
    itemRatling: 3.4, //calculate rating on daily bases in task
    restrauntId: 1,
    mode: 'non-veg',
    offer: 'get 40% Off for regular customer',
    description:
      'Chocolate ice cream, gooey chocolate cake and a chocolate bar, topped with chocolate sauce, whipped cream, crushed oreo cookies, chocolate waffles and gems. Calorific value per serving 780 Kcal Serving Size 238 gm',
    createdAt: '',
    modifyAt: '',
    avilableStatus: true,
    totalOrderCount: '40 total orders',
  },
  {
    id: 2,
    name: 'Dal Makhni',
    url: require('../../../assets/items/biryani.png'),
    price: 150,
    ladoPrice: 199,
    itemRatling: 3.8, //calculate rating on daily bases in task
    restrauntId: 1,
    mode: 'veg',
    offer: 'Free Delivery',
    description:
      'Chocolate ice cream, gooey chocolate cake and a chocolate bar, topped with chocolate sauce, whipped cream, crushed oreo cookies, chocolate waffles and gems. Calorific value per serving 780 Kcal Serving Size 238 gm',
    createdAt: '',
    modifyAt: '',
    avilableStatus: true,
    totalOrderCount: '30 total orders',
  },
  {
    id: 3,
    name: 'Egg Role',
    url: require('../../../assets/items/biryani.png'),
    price: 100,
    ladoPrice: 199,
    itemRatling: 4, //calculate rating on daily bases in task
    restrauntId: 1,
    mode: 'non-veg',
    offer: 'Free Delivery',
    description: 'Chocolate ice cream, gooey chocolate cake and a chocolate',
    createdAt: '',
    modifyAt: '',
    avilableStatus: true,
    totalOrderCount: '80 total orders',
  },
  {
    id: 4,
    name: 'Gobi Manchurian',
    url: require('../../../assets/items/biryani.png'),
    description: ' Lorem ipsum dolor sit amet',
    createdAt: '',
    modifyAt: '',
    avilableStatus: true,
    price: 150,
    ladoPrice: 199,
    itemRatling: 4.2, //calculate rating on daily bases in task
    restrauntId: 2,
    mode: 'veg',
    offer: 'Free Delivery',
    totalOrderCount: '90 total orders',
  },
  {
    id: 5,
    name: 'Veg Biryani',
    url: require('../../../assets/items/biryani.png'),
    price: 135,
    ladoPrice: 299,
    itemRatling: 4.3, //calculate rating on daily bases in task
    restrauntId: 2,
    mode: 'veg',
    offer: 'Free Delivery',
    description: ' Lorem ipsum dolor sit amet',
    createdAt: '',
    modifyAt: '',
    avilableStatus: true,
    totalOrderCount: '100 total orders',
  },
  {
    id: 6,
    name: 'Chicken 65',
    url: require('../../../assets/items/biryani.png'),
    price: 170,
    ladoPrice: 299,
    itemRatling: 4.8, //calculate rating on daily bases in task
    restrauntId: 2,
    mode: 'non-veg',
    offer: 'no Offer',
    description: ' Lorem ipsum dolor sit amet',
    createdAt: '',
    modifyAt: '',
    avilableStatus: true,
    totalOrderCount: '140 total orders',
  },
];

export const finalListOfItem = [
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
];

// give option to send offer to perchese item in less : restrount
