let a = [
  {
    id: 1,
    name: 'Biryani',
    image_url: require('../../../assets/items/biryani.png'),
    category: 'Non-Veg',
    sub_category: 'Rice',
  },
  {
    id: 2,
    name: 'Pizza',
    image_url: require('../../../assets/items/pizza.jpg'),
    category: 'Fast Food',
    sub_category: 'Italian',
  },
  {
    id: 3,
    name: 'Butter',
    image_url: require('../../../assets/items/paneer.png'),
    category: 'Veg',
    sub_category: 'Curry',
  },
  {
    id: 4,
    name: 'Burger',
    image_url: require('../../../assets/items/burger.png'),
    category: 'Fast Food',
    sub_category: 'American',
  },
  {
    id: 5,
    name: 'samosa',
    image_url: require('../../../assets/items/samosa.jpg'),
    category: 'Asian',
    sub_category: 'Chinese',
  },
  {
    id: 6,
    name: 'sweets',
    image_url: require('../../../assets/items/sweets.png'),
    category: 'Dessert',
    sub_category: 'Bakery',
  },
  {
    id: 7,
    name: 'kabab',
    image_url: require('../../../assets/items/kabab.png'),
    category: 'Meal',
    sub_category: 'Indian',
  },
];

export let listOFCategory = [...a];
// show restrount on the shorting of number of order and rating : high rating show first

export const listOFRestrount = [
  {
    id: 1,
    createdAt: '',
    modifyAt: '',
    openStatus: true,
    startAt: '',
    closeAt: '',
    restrountImage: '',
    name: 'Vishnu Story Fast Food House',
    shortName: 'VR House',
    mode: 'non-veg',
    location: 'Near Gadh devi mandir Toota pool, ranka more garhwa', // show only on the view of order restrount
    restrountOffer: 'Get 50% Off on every order',
    rating: '4.2',
    distance: '1 Km', // calulcate dynamic on the time of render and carding time
    averageDeliveryTime: '20 mins', // calculate on the backend on the gettting time
    description: '', // show only at the view of restrount page
    licenceNumber: '',
    ownerName: '',
    averageCookingTime: '',
    homeBanner: [
      {
        id: 1,
        url: require('../../../assets/restrount-welcome-img/biryani1.jpg'),
      },
      {
        id: 2,
        url: require('../../../assets/restrount-welcome-img/biryani2.jpg'),
      },
      {
        id: 3,
        url: require('../../../assets/restrount-welcome-img/biryani3.jpg'),
      },
    ],
  },
  {
    id: 2,
    createdAt: '',
    modifyAt: '',
    openStatus: false,
    startAt: '',
    closeAt: '',
    restrountImage: '',
    name: 'Good Food Kitchen',
    mode: 'veg,non-veg',
    location: 'Chiniya More',
    restrountOffer: 'Get 10% Off on Selected order',
    rating: '3.5',
    distance: '1.5Km', // calulcate dynamic on the time of render and carding time (bases of last location saved)
    averageDeliveryTime: '20min', // calculate on the backend on the gettting time (bases of last location order)
    description: '',
    licenceNumber: '',
    ownerName: '',
    homeBanner: [
      {
        id: 1,
        url: require('../../../assets/restrount-welcome-img/dalmakhni3.jpg'),
      },
      {
        id: 2,
        url: require('../../../assets/restrount-welcome-img/dalmakhni2.jpg'),
      },
      {
        id: 3,
        url: require('../../../assets/restrount-welcome-img/dalmakhni1.jpg'),
      },
    ],
  },
];

export const listOfItem = [
  {
    id: 1,
    name: 'Hayedrabadi biryani',
    url: require('../../../assets/items/biryani.png'),
    price: 250,
    ladoPrice: 299,
    itemRating: 3.4, //calculate rating on daily bases in task
    restaurantId: 1,
    mode: 'non-veg',
    offer: 'get 40% Off for regular customer',
    description:
      'Chocolate ice cream, gooey chocolate cake and a chocolate bar, topped with chocolate sauce, whipped cream, crushed oreo cookies, chocolate waffles and gems. Calorific value per serving 780 Kcal Serving Size 238 gm',
    createdAt: '',
    modifyAt: '',
    availableStatus: true,
    totalOrderCount: '40 total orders',
  },
  {
    id: 2,
    name: 'Dal Makhni',
    url: require('../../../assets/items/biryani.png'),
    price: 150,
    ladoPrice: 199,
    itemRating: 3.8, //calculate rating on daily bases in task
    restaurantId: 1,
    mode: 'veg',
    offer: 'Free Delivery',
    description:
      'Chocolate ice cream, gooey chocolate cake and a chocolate bar, topped with chocolate sauce, whipped cream, crushed oreo cookies, chocolate waffles and gems. Calorific value per serving 780 Kcal Serving Size 238 gm',
    createdAt: '',
    modifyAt: '',
    availableStatus: true,
    totalOrderCount: '30 total orders',
  },
  {
    id: 3,
    name: 'Egg Role',
    url: require('../../../assets/items/biryani.png'),
    price: 100,
    ladoPrice: 199,
    itemRating: 4, //calculate rating on daily bases in task
    restaurantId: 1,
    mode: 'non-veg',
    offer: 'Free Delivery',
    description: 'Chocolate ice cream, gooey chocolate cake and a chocolate',
    createdAt: '',
    modifyAt: '',
    availableStatus: true,
    totalOrderCount: '80 total orders',
  },
  {
    id: 4,
    name: 'Gobi Manchurian',
    url: require('../../../assets/items/biryani.png'),
    description: ' Lorem ipsum dolor sit amet',
    createdAt: '',
    modifyAt: '',
    availableStatus: true,
    price: 150,
    ladoPrice: 199,
    itemRating: 4.2, //calculate rating on daily bases in task
    restaurantId: 2,
    mode: 'veg',
    offer: 'Free Delivery',
    totalOrderCount: '90 total orders',
  },
  {
    id: 5,
    name: 'Veg Biryani',
    url: require('../../../assets/items/biryani.png'),
    price: 135,
    ladoPrice: 299,
    itemRating: 4.3, //calculate rating on daily bases in task
    restaurantId: 2,
    mode: 'veg',
    offer: 'Free Delivery',
    description: ' Lorem ipsum dolor sit amet',
    createdAt: '',
    modifyAt: '',
    availableStatus: true,
    totalOrderCount: '100 total orders',
  },
  {
    id: 6,
    name: 'Chicken 65',
    url: require('../../../assets/items/biryani.png'),
    price: 170,
    ladoPrice: 299,
    itemRating: 4.8, //calculate rating on daily bases in task
    restaurantId: 2,
    mode: 'non-veg',
    offer: 'no Offer',
    description: ' Lorem ipsum dolor sit amet',
    createdAt: '',
    modifyAt: '',
    availableStatus: true,
    totalOrderCount: '140 total orders',
  },
];

export const finalListOfItem = [
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
  ...listOFRestrount,
];

//TODO: Not allow to add
export const snacksAndDrinks = [
  {
    id: 1,
    restaurantId: 1,
    name: 'Water Bottle',
    brand: 'Aqua',
    category: 'Drink',
    price: 20,
    quantity: '1L',
    inStock: true,
    description: 'Chilled mineral water bottle, 1L',
    imageUrl: require('../../../assets/bottel.png'),
    sku: 'DRK-AQUA-1L',
    createdAt: '2025-04-26T10:00:00Z',
    updatedAt: '2025-04-26T10:00:00Z',
  },
  {
    id: 2,
    restaurantId: 1,
    name: 'Coca-Cola Can',
    brand: 'Coca-Cola',
    category: 'Soft Drink',
    price: 35,
    quantity: '330ml',
    inStock: true,
    description: 'Chilled Coca-Cola soft drink in can',
    imageUrl: require('../../../assets/bottel.png'),
    sku: 'DRK-COKE-330',
    createdAt: '2025-04-26T10:00:00Z',
    updatedAt: '2025-04-26T10:00:00Z',
  },
  {
    id: 3,
    restaurantId: 1,
    name: 'Lays Classic Salted',
    brand: 'Lays',
    category: 'Snack',
    price: 20,
    quantity: '52g',
    inStock: true,
    description: 'Crunchy salted potato chips',
    imageUrl: require('../../../assets/bottel.png'),
    sku: 'SNK-LAYS-SALTED',
    createdAt: '2025-04-26T10:00:00Z',
    updatedAt: '2025-04-26T10:00:00Z',
  },
  {
    id: 4,
    restaurantId: 1,
    name: 'Sprite Bottle',
    brand: 'Sprite',
    category: 'Soft Drink',
    price: 40,
    quantity: '500ml',
    inStock: false,
    description: 'Lemon-lime flavored soda bottle',
    imageUrl: require('../../../assets/bottel.png'),
    sku: 'DRK-SPRITE-500',
    createdAt: '2025-04-26T10:00:00Z',
    updatedAt: '2025-04-26T10:00:00Z',
  },
  {
    id: 5,
    restaurantId: 1,
    name: 'Pepsi Can',
    brand: 'Pepsi',
    category: 'Soft Drink',
    price: 35,
    quantity: '330ml',
    inStock: true,
    description: 'Chilled Pepsi cola drink in a can',
    imageUrl: require('../../../assets/bottel.png'),
    sku: 'DRK-PEPSI-330',
    createdAt: '2025-04-26T10:00:00Z',
    updatedAt: '2025-04-26T10:00:00Z',
  },
  {
    id: 6,
    restaurantId: 1,
    name: 'Bisleri Water',
    brand: 'Bisleri',
    category: 'Drink',
    price: 25,
    quantity: '1L',
    inStock: true,
    description: 'Packaged drinking water - Bisleri brand',
    imageUrl: require('../../../assets/bottel.png'),
    sku: 'DRK-BISLERI-1L',
    createdAt: '2025-04-26T10:00:00Z',
    updatedAt: '2025-04-26T10:00:00Z',
  },
  {
    id: 7,
    restaurantId: 1,
    name: 'Oreo Cookies',
    brand: 'Oreo',
    category: 'Snack',
    price: 30,
    quantity: '120g',
    inStock: true,
    description: 'Cream-filled chocolate cookies',
    imageUrl: require('../../../assets/bottel.png'),
    sku: 'SNK-OREO-120',
    createdAt: '2025-04-26T10:00:00Z',
    updatedAt: '2025-04-26T10:00:00Z',
  },
  {
    id: 8,
    restaurantId: 1,
    name: 'Red Bull',
    brand: 'Red Bull',
    category: 'Energy Drink',
    price: 110,
    quantity: '250ml',
    inStock: true,
    description: 'Energy drink with caffeine and taurine',
    imageUrl: require('../../../assets/bottel.png'),
    sku: 'DRK-REDBULL-250',
    createdAt: '2025-04-26T10:00:00Z',
    updatedAt: '2025-04-26T10:00:00Z',
  },
  {
    id: 9,
    restaurantId: 1,
    name: 'Kurkure Masala Munch',
    brand: 'Kurkure',
    category: 'Snack',
    price: 20,
    quantity: '50g',
    inStock: true,
    description: 'Spicy crunchy corn snack',
    imageUrl: require('../../../assets/bottel.png'),
    sku: 'SNK-KURKURE-50',
    createdAt: '2025-04-26T10:00:00Z',
    updatedAt: '2025-04-26T10:00:00Z',
  },
  {
    id: 10,
    restaurantId: 1,
    name: 'Mountain Dew',
    brand: 'Mountain Dew',
    category: 'Soft Drink',
    price: 40,
    quantity: '500ml',
    inStock: false,
    description: 'Citrus-flavored soft drink',
    imageUrl: require('../../../assets/bottel.png'),
    sku: 'DRK-MTDEW-500',
    createdAt: '2025-04-26T10:00:00Z',
    updatedAt: '2025-04-26T10:00:00Z',
  },
];

// give option to send offer to perchese item in less : restrount

export const user = {
  name: 'Dilshad Ansari',
  phoneNo: 7903715443,
  location: 'Near Gadh devi mandir Toota pool, ranka more garhwa',
};

//------------------------------------------ Acctual schema  -------------------------------------------------------------//

//TODO: user table schema
const finalUser = {
  name: 'Dilshad Ansari',
  phoneNo: '7903715443',
  passwordHash: '$2b$10$Abcdefghijklmnopqrstuvwxyz123456',
  isPhoneVerified: false,
  otp: {
    code: '123456',
    expiresAt: '2025-05-01T15:00:00.000Z',
  },
  addresses: [
    {
      fullLocation: 'Uchri more garhwa',
      landMark: 'Near petrol pump',
      label: 'home',
    },
    {
      fullLocation: 'Road no 4, Madarsa Road, Garhwa',
      landMark: 'Near bus stop',
      label: 'work',
    },
  ],
  defaultAddressIndex: 0,
  role: 'user',
  createdAt: '2025-05-01T10:00:00.000Z',
};

//TODO: hotel schema

const first = {
  id: 1,
  createdAt: '2025-05-01T10:00:00Z',
  modifyAt: '2025-05-01T10:00:00Z',
  open: true,
  startAt: '09:00 AM',
  closeAt: '10:00 PM',
  restaurantImage: 'https://example.com/restaurant-image.jpg',
  name: 'Vishnu Story Fast Food House',
  shortName: 'VR House',
  mode: 'non-veg',
  location: 'Near Gadh Devi Mandir, Toota Pool, Ranka More, Garhwa',
  restaurantOffer: 'Get 50% Off on every order',
  rating: '4.2',
  totalOrderDeliver: 10,
  distance: '1 Km', // dynamically calculated
  averageDeliveryTime: '20 mins', // dynamically calculated
  description: 'Best fast food joint for spicy lovers.',
  licenceNumber: 'GARHWA1234',
  ownerName: 'Vishnu Kumar',
  averageCookingTime: '15 mins',
  homeBanner: [
    {
      id: 1,
      url: require('../../../assets/restrount-welcome-img/biryani1.jpg'),
    },
    {
      id: 2,
      url: require('../../../assets/restrount-welcome-img/biryani2.jpg'),
    },
    {
      id: 3,
      url: require('../../../assets/restrount-welcome-img/biryani3.jpg'),
    },
  ],
  restaurantItems: [
    {
      id: 1,
      name: 'Hayedrabadi biryani',
      url: require('../../../assets/items/biryani.png'),
      price: 250,
      ladoPrice: 299,
      itemRating: 3.4, //calculate rating on daily bases in task
      restaurantId: 1,
      mode: 'non-veg',
      offer: 'get 40% Off for regular customer',
      description:
        'Chocolate ice cream, gooey chocolate cake and a chocolate bar, topped with chocolate sauce, whipped cream, crushed oreo cookies, chocolate waffles and gems. Calorific value per serving 780 Kcal Serving Size 238 gm',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      totalOrderCount: '40 total orders',
    },
    {
      id: 2,
      name: 'Dal Makhni',
      url: require('../../../assets/items/biryani.png'),
      price: 150,
      ladoPrice: 199,
      itemRating: 3.8, //calculate rating on daily bases in task
      restaurantId: 1,
      mode: 'veg',
      offer: 'Free Delivery',
      description:
        'Chocolate ice cream, gooey chocolate cake and a chocolate bar, topped with chocolate sauce, whipped cream, crushed oreo cookies, chocolate waffles and gems. Calorific value per serving 780 Kcal Serving Size 238 gm',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      totalOrderCount: '30 total orders',
    },
    {
      id: 3,
      name: 'Egg Role',
      url: require('../../../assets/items/biryani.png'),
      price: 100,
      ladoPrice: 199,
      itemRating: 4, //calculate rating on daily bases in task
      restaurantId: 1,
      mode: 'non-veg',
      offer: 'Free Delivery',
      description: 'Chocolate ice cream, gooey chocolate cake and a chocolate',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      totalOrderCount: '80 total orders',
    },
    {
      id: 4,
      name: 'Gobi Manchurian',
      url: require('../../../assets/items/biryani.png'),
      description: ' Lorem ipsum dolor sit amet',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      price: 150,
      ladoPrice: 199,
      itemRating: 4.2, //calculate rating on daily bases in task
      restaurantId: 1,
      mode: 'veg',
      offer: 'Free Delivery',
      totalOrderCount: '90 total orders',
    },
    {
      id: 5,
      name: 'Veg Biryani',
      url: require('../../../assets/items/biryani.png'),
      price: 135,
      ladoPrice: 299,
      itemRating: 4.3, //calculate rating on daily bases in task
      restaurantId: 1,
      mode: 'veg',
      offer: 'Free Delivery',
      description: ' Lorem ipsum dolor sit amet',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      totalOrderCount: '100 total orders',
    },
    {
      id: 6,
      name: 'Chicken 65',
      url: require('../../../assets/items/biryani.png'),
      price: 170,
      ladoPrice: 299,
      itemRating: 4.8, //calculate rating on daily bases in task
      restaurantId: 1,
      mode: 'non-veg',
      offer: 'no Offer',
      description: ' Lorem ipsum dolor sit amet',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      totalOrderCount: '140 total orders',
    },
  ],
  snacksAndDrinks: [
    {
      id: 1,
      restaurantId: 1,
      name: 'Water Bottle',
      brand: 'Aqua',
      category: 'Drink',
      price: 20,
      anyDiscount: false,
      quantity: '1L',
      inStock: true,
      description: 'Chilled mineral water bottle, 1L',
      imageUrl: 'https://example.com/assets/bottle.png',
      sku: 'DRK-AQUA-1L',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 2,
      restaurantId: 1,
      name: 'Coca-Cola Can',
      brand: 'Coca-Cola',
      category: 'Soft Drink',
      price: 35,
      quantity: '330ml',
      inStock: true,
      anyDiscount: false,
      description: 'Chilled Coca-Cola soft drink in can',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-COKE-330',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 3,
      restaurantId: 1,
      name: 'Lays Classic Salted',
      brand: 'Lays',
      category: 'Snack',
      price: 20,
      quantity: '52g',
      inStock: true,
      anyDiscount: false,
      description: 'Crunchy salted potato chips',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'SNK-LAYS-SALTED',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 4,
      restaurantId: 1,
      name: 'Sprite Bottle',
      brand: 'Sprite',
      category: 'Soft Drink',
      price: 40,
      quantity: '500ml',
      inStock: false,
      anyDiscount: false,
      description: 'Lemon-lime flavored soda bottle',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-SPRITE-500',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 5,
      restaurantId: 1,
      name: 'Pepsi Can',
      brand: 'Pepsi',
      category: 'Soft Drink',
      price: 35,
      quantity: '330ml',
      inStock: true,
      anyDiscount: false,
      description: 'Chilled Pepsi cola drink in a can',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-PEPSI-330',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 6,
      restaurantId: 1,
      name: 'Bisleri Water',
      brand: 'Bisleri',
      category: 'Drink',
      price: 25,
      quantity: '1L',
      inStock: true,
      anyDiscount: false,
      description: 'Packaged drinking water - Bisleri brand',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-BISLERI-1L',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 7,
      restaurantId: 1,
      name: 'Oreo Cookies',
      brand: 'Oreo',
      category: 'Snack',
      price: 30,
      quantity: '120g',
      inStock: true,
      anyDiscount: false,
      description: 'Cream-filled chocolate cookies',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'SNK-OREO-120',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 8,
      restaurantId: 1,
      name: 'Red Bull',
      brand: 'Red Bull',
      category: 'Energy Drink',
      price: 110,
      quantity: '250ml',
      inStock: true,
      anyDiscount: false,
      description: 'Energy drink with caffeine and taurine',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-REDBULL-250',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 9,
      restaurantId: 1,
      name: 'Kurkure Masala Munch',
      brand: 'Kurkure',
      category: 'Snack',
      price: 20,
      quantity: '50g',
      inStock: true,
      anyDiscount: false,
      description: 'Spicy crunchy corn snack',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'SNK-KURKURE-50',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 10,
      restaurantId: 1,
      name: 'Mountain Dew',
      brand: 'Mountain Dew',
      category: 'Soft Drink',
      price: 40,
      quantity: '500ml',
      inStock: false,
      anyDiscount: false,
      description: 'Citrus-flavored soft drink',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-MTDEW-500',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
  ],
};

const second = {
  id: 2,
  createdAt: '2025-05-01T10:00:00Z',
  modifyAt: '2025-05-01T10:00:00Z',
  open: true,
  startAt: '09:00 AM',
  closeAt: '10:00 PM',
  restaurantImage: 'https://example.com/restaurant-image.jpg',
  name: 'Good Food Kitchen',
  shortName: 'GD Kitchen',
  mode: 'veg,non-veg',
  location: 'Chiniya More',
  restaurantOffer: 'Get 10% Off on Selected order',
  rating: '3.5',
  totalOrderDeliver: 10,
  distance: '1 Km', // dynamically calculated
  averageDeliveryTime: '20 mins', // dynamically calculated
  description: 'Best fast food joint for spicy lovers.',
  licenceNumber: 'GARHWA1234',
  ownerName: 'Vishnu Kumar',
  averageCookingTime: '15 mins',
  homeBanner: [
    {
      id: 1,
      url: require('../../../assets/restrount-welcome-img/dalmakhni3.jpg'),
    },
    {
      id: 2,
      url: require('../../../assets/restrount-welcome-img/dalmakhni2.jpg'),
    },
    {
      id: 3,
      url: require('../../../assets/restrount-welcome-img/dalmakhni1.jpg'),
    },
  ],
  restaurantItems: [
    {
      id: 1,
      name: 'Hayedrabadi biryani',
      url: require('../../../assets/items/biryani.png'),
      price: 250,
      ladoPrice: 299,
      itemRating: 3.4, //calculate rating on daily bases in task
      restaurantId: 2,
      mode: 'non-veg',
      offer: 'get 40% Off for regular customer',
      description:
        'Chocolate ice cream, gooey chocolate cake and a chocolate bar, topped with chocolate sauce, whipped cream, crushed oreo cookies, chocolate waffles and gems. Calorific value per serving 780 Kcal Serving Size 238 gm',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      totalOrderCount: '40 total orders',
    },
    {
      id: 2,
      name: 'Dal Makhni',
      url: require('../../../assets/items/biryani.png'),
      price: 150,
      ladoPrice: 199,
      itemRating: 3.8, //calculate rating on daily bases in task
      restaurantId: 2,
      mode: 'veg',
      offer: 'Free Delivery',
      description:
        'Chocolate ice cream, gooey chocolate cake and a chocolate bar, topped with chocolate sauce, whipped cream, crushed oreo cookies, chocolate waffles and gems. Calorific value per serving 780 Kcal Serving Size 238 gm',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      totalOrderCount: '30 total orders',
    },
    {
      id: 3,
      name: 'Egg Role',
      url: require('../../../assets/items/biryani.png'),
      price: 100,
      ladoPrice: 199,
      itemRating: 4, //calculate rating on daily bases in task
      restaurantId: 2,
      mode: 'non-veg',
      offer: 'Free Delivery',
      description: 'Chocolate ice cream, gooey chocolate cake and a chocolate',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      totalOrderCount: '80 total orders',
    },
    {
      id: 4,
      name: 'Gobi Manchurian',
      url: require('../../../assets/items/biryani.png'),
      description: ' Lorem ipsum dolor sit amet',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      price: 150,
      ladoPrice: 199,
      itemRating: 4.2, //calculate rating on daily bases in task
      restaurantId: 2,
      mode: 'veg',
      offer: 'Free Delivery',
      totalOrderCount: '90 total orders',
    },
    {
      id: 5,
      name: 'Veg Biryani',
      url: require('../../../assets/items/biryani.png'),
      price: 135,
      ladoPrice: 299,
      itemRating: 4.3, //calculate rating on daily bases in task
      restaurantId: 2,
      mode: 'veg',
      offer: 'Free Delivery',
      description: ' Lorem ipsum dolor sit amet',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      totalOrderCount: '100 total orders',
    },
    {
      id: 6,
      name: 'Chicken 65',
      url: require('../../../assets/items/biryani.png'),
      price: 170,
      ladoPrice: 299,
      itemRating: 4.8, //calculate rating on daily bases in task
      restaurantId: 2,
      mode: 'non-veg',
      offer: 'no Offer',
      description: ' Lorem ipsum dolor sit amet',
      createdAt: '2025-04-26T10:00:00Z',
      modifyAt: '2025-04-26T10:00:00Z',
      availableStatus: true,
      totalOrderCount: '140 total orders',
    },
  ],
  snacksAndDrinks: [
    {
      id: 1,
      restaurantId: 2,
      name: 'Water Bottle',
      brand: 'Aqua',
      category: 'Drink',
      price: 20,
      anyDiscount: false,
      quantity: '1L',
      inStock: true,
      description: 'Chilled mineral water bottle, 1L',
      imageUrl: 'https://example.com/assets/bottle.png',
      sku: 'DRK-AQUA-1L',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 2,
      restaurantId: 2,
      name: 'Coca-Cola Can',
      brand: 'Coca-Cola',
      category: 'Soft Drink',
      price: 35,
      quantity: '330ml',
      inStock: true,
      anyDiscount: false,
      description: 'Chilled Coca-Cola soft drink in can',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-COKE-330',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 3,
      restaurantId: 2,
      name: 'Lays Classic Salted',
      brand: 'Lays',
      category: 'Snack',
      price: 20,
      quantity: '52g',
      inStock: true,
      anyDiscount: false,
      description: 'Crunchy salted potato chips',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'SNK-LAYS-SALTED',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 4,
      restaurantId: 2,
      name: 'Sprite Bottle',
      brand: 'Sprite',
      category: 'Soft Drink',
      price: 40,
      quantity: '500ml',
      inStock: false,
      anyDiscount: false,
      description: 'Lemon-lime flavored soda bottle',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-SPRITE-500',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 5,
      restaurantId: 2,
      name: 'Pepsi Can',
      brand: 'Pepsi',
      category: 'Soft Drink',
      price: 35,
      quantity: '330ml',
      inStock: true,
      anyDiscount: false,
      description: 'Chilled Pepsi cola drink in a can',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-PEPSI-330',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 6,
      restaurantId: 2,
      name: 'Bisleri Water',
      brand: 'Bisleri',
      category: 'Drink',
      price: 25,
      quantity: '1L',
      inStock: true,
      anyDiscount: false,
      description: 'Packaged drinking water - Bisleri brand',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-BISLERI-1L',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 7,
      restaurantId: 2,
      name: 'Oreo Cookies',
      brand: 'Oreo',
      category: 'Snack',
      price: 30,
      quantity: '120g',
      inStock: true,
      anyDiscount: false,
      description: 'Cream-filled chocolate cookies',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'SNK-OREO-120',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 8,
      restaurantId: 2,
      name: 'Red Bull',
      brand: 'Red Bull',
      category: 'Energy Drink',
      price: 110,
      quantity: '250ml',
      inStock: true,
      anyDiscount: false,
      description: 'Energy drink with caffeine and taurine',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-REDBULL-250',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 9,
      restaurantId: 2,
      name: 'Kurkure Masala Munch',
      brand: 'Kurkure',
      category: 'Snack',
      price: 20,
      quantity: '50g',
      inStock: true,
      anyDiscount: false,
      description: 'Spicy crunchy corn snack',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'SNK-KURKURE-50',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
    {
      id: 10,
      restaurantId: 2,
      name: 'Mountain Dew',
      brand: 'Mountain Dew',
      category: 'Soft Drink',
      price: 40,
      quantity: '500ml',
      inStock: false,
      anyDiscount: false,
      description: 'Citrus-flavored soft drink',
      imageUrl: require('../../../assets/bottel.png'),
      sku: 'DRK-MTDEW-500',
      createdAt: '2025-04-26T10:00:00Z',
      updatedAt: '2025-04-26T10:00:00Z',
    },
  ],
};

export const finalList = [first, second];
